apiVersion: v1
kind: PersistentVolume
metadata:
  name: "mypv"
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  nfs:
    server: "192.168.0.111"
    path: "/k8s_data"  